include Makefile.common

TARGET := $(SNUCLROOT)/lib/libsnucl_cpu.so
CXX    := g++

CXX_FLAGS += -DCPU_PLATFORM

SOURCES += $(wildcard cpu/*.cpp)

OBJ_DIR=objs/cpu

SUBDIRS=cpu
OBJ_SUBDIRS=$(patsubst %,$(OBJ_DIR)/%,$(SUBDIRS))
DEPS_DIR=$(patsubst %,$(OBJ_DIR)/.deps/%,$(SUBDIRS))

include Makefile.rules
